### ISSUE TITLE
Installation, not working for me

### ISSUE THREAD

**Issue by MathieuMarteau** [Log1x/sage-directives#101]
Hello everyone!

Apologies in advance for my English. I wanted to try installing "sage-directives" on a test project.

So, I ran the command "composer require log1x/sage-directives" at the root of my theme, and then I created an input field with the name "test," which I associated with a block (https://github.com/MWDelaney/sage-acf-wp-blocks).

My blade file (basic):

```blade
{{--
  Title: Testimonial
  Description: Customer testimonial
  Category: formatting
  Icon: admin-comments
  Keywords: testimonial quote
  Mode: edit
  Align: left
  PostTypes: page post
  SupportsAlign: center
  SupportsMode: false
  SupportsMultiple: true
  EnqueueStyle: styles/style.css
  EnqueueScript: scripts/script.js
  EnqueueAssets: path/to/asset
--}}

<h1 class="">
  @field('test')
</h1>
```

I ran the "composer require" command at the root of the Sage theme (I have installed and uninstalled it several times).

Here's the result:

![Capture d’écran 2023-08-01 à 11 41 20](https://github.com/Log1x/sage-directives/assets/98155376/4040acd1-181f-4e07-84d0-f519d29b5d4a)

![Capture d’écran 2023-08-01 à 11 49 57](https://github.com/Log1x/sage-directives/assets/98155376/c21853cc-82c1-41df-8807-ee4ed0c8d6be)

The code is not being interpreted. What did I forget to do? Please note that I am using the latest version of Sage 10 and Bedrock, with PHP 8.1.9.

Thanks in advance!
Mathieu Marteau

**Comment by Log1x** [comment]
Does running `wp acorn optimize:clear` help? Sometimes the [post-autoload-dump step](https://roots.io/acorn/docs/installation/#installing-acorn-with-composer) gets over looked and packages will not autoload properly without it.

Otherwise, I just spun up a fresh Bedrock+Sage 10 and tried out `@repeat(5) test @endrepeat` in `index.blade.php` and it worked without any issues.

By the way, you might need to do `composer self-update` and `composer upgrade` to fix those deprecation notices. Make sure you have version control before running `composer upgrade` though. :)

**Comment by MathieuMarteau** [comment]
Indeed, it works with the command, I wouldn't have thought of it! I'll be able to try all that now. Many thanks for this project! :)

Have a great day!
