### ISSUE TITLE
Sage 10 usage

### ISSUE THREAD

**Issue by ouun** [Log1x/sage-directives#32]
Dear @Log1x,
thank you very much for this! It is a very usefule addition to the sage theme.
However I am not sure how to integrate it with Sage 10. I added it via `composer require  Log1x /
sage-directives` and assumed that it is auto loaded via composer. But somehow the directives are not working. Is there a second step which I am missing? 

Best regards,

Philipp

**Comment by Log1x** [comment]
Hi.

Are you adding it in the theme's `composer.json`? If so, it should "just work". Otherwise, you can try clearing your view cache:

```sh
$ yarn clean:views
```

**Comment by Log1x** [comment]
Closing this. Let me know if you still need help.

**Comment by ouun** [comment]
Hi @Log1x,
sorry for my late reply. I was afk for a week.
However I double checked that the package is added to the correct composer.json and flushed the view caches. It is all as it should, but the directives are not working... 
So I set up a complete new sage 10 theme via

`composer create-project roots/sage test dev-10.0.0-dev`

... added `Log1x/sage-directives` via ...

`composer require Log1x/sage-directives`

... reloaded autoload via ...

`composer dump-autoload`

... and even flushed the caches via ...

`yarn clean:views`

... but still no luck. In order to get the directives working, it requires me to load the Classes e.g. from `setup.php?`. 

````
$directives      = new \Log1x\SageDirectives\Directives();
$directives_util = new \Log1x\SageDirectives\Util();
````

So that was confusing me as I assumed that it "just works" as you said. 

Kind regards!

**Comment by ouun** [comment]
@Log1x sorry for pushing this again but I'm still not sure whether it is your intention to have the Classes called as above or just autoloaded.

**Comment by 1pix** [comment]
Hi @Log1x ,

First, thank you for all your great work around roots/sage, I use almost all of it everyday.
I just let some  feedback here, because I saw the same problem.

In my case, I have settup a _wp-config_ that require composer-autoload from the sage-10 theme folder, because I added dotenv and have used the composer config in the sage theme to do that(and not root directory, I know I could also use Bedrock, but it's more simple this time).

Everything was working perfectly before requiring autoload in wp-config.
Since the change, everything works (all others composer package), except sage-directives not loading, until I load the class in setup.php as @ouun.

Is there a problem with that kind of setup ?

Thanks for your feedback, and again for the amazing work you bring to the community.
Kind regards,
Sylvain

My wp-config.php
```php
/*
 * WORPDRESS MULTIPLE ENVIRONMENT
*/

$activetheme = 'my-theme';

// Define default theme
if (!defined('WP_DEFAULT_THEME')) {
    define('WP_DEFAULT_THEME', $activetheme);
}

/** Include environment specific configuration. */
require_once(dirname(__FILE__) . '/wp-content/themes/' . $activetheme . '/vendor/autoload.php');
require_once(dirname(__FILE__) . '/wp-content/themes/' . $activetheme . '/wp-config-env.php');

/** Absolute path to the WordPress directory. */
if (!defined('ABSPATH')) {
    define('ABSPATH', dirname(__FILE__) . '/');
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
```

**Comment by 1pix** [comment]
Hi @ouun did you find a solution at your problem ? Very strange for me, problem appears only after auto-loading from wp-config (and all others php packages are loading fine).

@Log1x The only difference i see is that sage-directive autoload "files" and not psr-4 classes/namespace (as sage-svg or acf-composer for exemple), is there something to add with that particularity ? sorry I'm not very aware of composer process :/

Thank you for your help, kind regards,
S

**Comment by hofmannsven** [comment]
It worked after I cleared the view cache with Acorn:
```
wp acorn view:clear
```
