### ISSUE TITLE
Shortcodes can't be used within ACF fields

### ISSUE THREAD

**Issue by theimaginaire** [Log1x/sage-directives#36]
Love the directives -- having an issue when coming to use them in the real world though -- we use a shortcode of [phone] for client websites so we can easily swap phone numbers if they change etc. The @field, @sub and @option directives don't allow this.

In raw php, you'd have to run:

`echo do_shortcode(get_field('phone', 'options'));`

The above still works even if there are no shortcodes found -- is it worth just adding that to the core?

**Comment by Log1x** [comment]
I'm assuming you tried `@shortcode(get_field('phone', 'options'))` and got thrown an error due to Blade getting confused due to the values passed to `get_field()`

I would probably just create a Composer (or Controller if Sage 9) for `$phone` and have it return `get_field('phone', 'options') ?? false` and then do `@shortcode($phone)`

**Comment by theimaginaire** [comment]
Ok -- just wondered if it was worth just making a universal change within sage directives instead as there are likely to be a lot of shortcodes used by the wider community?

**Comment by theimaginaire** [comment]
Just in case anyone else stumbles across this, the `@shortcode(get_field('field'))` works
