### ISSUE TITLE
Can't get this to work - Sage 9.0.10

### ISSUE THREAD

**Issue by jarimbi** [Log1x/sage-directives#62]
I ran composer 'require log1x/sage-directives' and then 'yarn install.' (inside my theme folder)
Also ran plain 'yarn' and 'yarn build'.
Note that 'yarn run docs:build' returns an error.

I do see the folder vendor/log1x/sage-directives and its contents.
I have uploaded that new folder to the server and tried out some directives but none of those are generating anything.

Example: @isnotnull($test) outputs just that exact text.

What do I need to check to make sure the sage-directives are correctly installed?
I feel like a step is missing...

**Comment by catgofire** [comment]
@jarimbi Make sure something like `"log1x/sage-directives": "^1.1",` is in the `"require"` section of `composer.json`, and make sure it's not listed in `package.json` — this is a PHP package and has nothing to do with yarn.

Are you able to run a `composer install` on the server directly, instead of uploading the `vendor/` directory?

**Comment by jarimbi** [comment]
@catgofire: thanks for your reply. I cannot run composer on the server, but I did get it to work.

I also had to copy over:
vendor/composer/installed.json
vendor/composer/installed.php
vendor/composer/autoload_files.php
vendor/composer/autoload_static.php

Then it still did not work, but after trying out a bunch of things, I think the trick was to delete the cache folder (uploads/cache)

I hope this helps someone struggling with the same issue.
